export const words = [
  { word: "apple", hint: "A common fruit that keeps doctors away" },
  { word: "river", hint: "Flows but never walks" },
  { word: "chair", hint: "You sit on it daily" },
  { word: "house", hint: "A place people live" },
  { word: "light", hint: "Opposite of dark" },
  { word: "bread", hint: "Often eaten with butter" },
  { word: "clock", hint: "Shows time on a wall" },
  { word: "phone", hint: "Used to call or text someone" },
  { word: "water", hint: "You drink it to stay alive" },
  { word: "plant", hint: "Needs sunlight and water to grow" },
  { word: "stone", hint: "Hard and found on the ground" },
  { word: "cloud", hint: "Floats in the sky" },
  { word: "table", hint: "You eat meals on it" },
  { word: "shirt", hint: "You wear it on your upper body" },
  { word: "shoes", hint: "You wear them on your feet" },
  { word: "glass", hint: "You drink from it" },
  { word: "plate", hint: "Holds your food" },
  { word: "spoon", hint: "Used for eating soup" },
  { word: "knife", hint: "Used to cut things" },
  { word: "paper", hint: "Used for writing or printing" },
  { word: "pencil", hint: "Used to write but can be erased" },
  { word: "school", hint: "Place where students learn" },
  { word: "teacher", hint: "Helps students learn" },
  { word: "student", hint: "Learns in a classroom" },
  { word: "music", hint: "Something you listen to for enjoyment" },
  { word: "dance", hint: "Moving your body to rhythm" },
  { word: "movie", hint: "Watched on a screen for entertainment" },
  { word: "story", hint: "Tells events or imagination" },
  { word: "dream", hint: "Happens when you sleep" },
  { word: "sleep", hint: "You do it every night" },
  { word: "smile", hint: "Expression of happiness" },
  { word: "laugh", hint: "Sound you make when amused" },
  { word: "happy", hint: "Feeling of joy" },
  { word: "angry", hint: "Feeling of strong annoyance" },
  { word: "tired", hint: "Feeling the need to rest" },
  { word: "quick", hint: "Opposite of slow" },
  { word: "slow", hint: "Opposite of fast" },
  { word: "clean", hint: "Free from dirt" },
  { word: "dirty", hint: "Not clean" },
  { word: "sweet", hint: "Taste like sugar" },
  { word: "bitter", hint: "Opposite of sweet in taste" },
  { word: "salty", hint: "Taste of the ocean" },
  { word: "spicy", hint: "Can make your mouth feel hot" },
  { word: "sugar", hint: "Used to make things sweet" },
  { word: "honey", hint: "Made by bees" },
  { word: "butter", hint: "Spread on bread" },
  { word: "cheese", hint: "Dairy product, often yellow" },
  { word: "fruit", hint: "Sweet food from plants" },
  { word: "grape", hint: "Small fruit, can make wine" },
  { word: "mango", hint: "Tropical sweet fruit" },
  { word: "lemon", hint: "Sour yellow fruit" },
  { word: "orange", hint: "Citrus fruit and a color" },
  { word: "banana", hint: "Long yellow fruit" },
  { word: "tomato", hint: "Red and used in cooking" },
  { word: "carrot", hint: "Orange vegetable, good for eyes" },
  { word: "onion", hint: "Can make you cry when cutting" },
  { word: "pepper", hint: "Adds spice to food" },
  { word: "coffee", hint: "Drink that helps you stay awake" },
  { word: "tea", hint: "Hot drink made from leaves" },
  { word: "juice", hint: "Drink made from fruits" },
  { word: "bottle", hint: "Used to carry liquids" },
  { word: "basket", hint: "Used to carry items" },
  { word: "window", hint: "Lets you see outside" },
  { word: "door", hint: "You open it to enter" },
  { word: "floor", hint: "You walk on it indoors" },
  { word: "ceiling", hint: "Above your head inside a room" },
  { word: "garden", hint: "Place where plants grow at home" },
  { word: "street", hint: "Cars drive on it" },
  { word: "market", hint: "Place to buy and sell goods" },
  { word: "store", hint: "Where you buy items" },
  { word: "money", hint: "Used to buy things" },
  { word: "price", hint: "Cost of an item" },
  { word: "value", hint: "Worth of something" },
  { word: "gift", hint: "Given without payment" },
  { word: "party", hint: "People gather to celebrate" },
  { word: "music", hint: "Played at celebrations" },
  { word: "game", hint: "Played for fun" },
  { word: "sport", hint: "Physical activity competition" },
  { word: "team", hint: "Group working together" },
  { word: "score", hint: "Points gained in a game" },
  { word: "travel", hint: "Going from one place to another" },
  { word: "journey", hint: "Trip from start to end" },
  { word: "ticket", hint: "Needed for transport or events" },
  { word: "train", hint: "Runs on tracks" },
  { word: "plane", hint: "Flies in the sky" },
  { word: "beach", hint: "Sandy place near water" },
  { word: "ocean", hint: "Large body of salt water" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "forest", hint: "Large area full of trees" },
  { word: "desert", hint: "Dry place with little water" },
  { word: "apple", hint: "A fruit that keeps doctors away" },
  { word: "river", hint: "Flows but never walks" },
  { word: "chair", hint: "You sit on it" },
  { word: "house", hint: "A place to live" },
  { word: "light", hint: "Opposite of dark" },
  { word: "bread", hint: "Often eaten with butter" },
  { word: "clock", hint: "Shows time" },
  { word: "phone", hint: "Used to call people" },
  { word: "water", hint: "You drink it daily" },
  { word: "plant", hint: "Needs sun and water" },
  { word: "stone", hint: "Hard and on the ground" },
  { word: "cloud", hint: "Floats in the sky" },
  { word: "table", hint: "Used for eating meals" },
  { word: "shirt", hint: "Worn on upper body" },
  { word: "shoes", hint: "Worn on feet" },
  { word: "glass", hint: "Used for drinking" },
  { word: "plate", hint: "Holds your food" },
  { word: "spoon", hint: "Used for soup" },
  { word: "knife", hint: "Used to cut food" },
  { word: "paper", hint: "Used for writing" },
  { word: "pencil", hint: "Can be erased" },
  { word: "school", hint: "Place to learn" },
  { word: "teacher", hint: "Helps students learn" },
  { word: "student", hint: "Person who learns" },
  { word: "music", hint: "You listen to it" },
  { word: "dance", hint: "Move to rhythm" },
  { word: "movie", hint: "Watched on screen" },
  { word: "story", hint: "Tells events" },
  { word: "dream", hint: "Happens in sleep" },
  { word: "sleep", hint: "You do it at night" },
  { word: "smile", hint: "Shows happiness" },
  { word: "laugh", hint: "Sound of joy" },
  { word: "happy", hint: "Feeling of joy" },
  { word: "angry", hint: "Feeling upset" },
  { word: "tired", hint: "Need to rest" },
  { word: "quick", hint: "Opposite of slow" },
  { word: "clean", hint: "Not dirty" },
  { word: "dirty", hint: "Not clean" },
  { word: "sweet", hint: "Taste like sugar" },
  { word: "bitter", hint: "Opposite of sweet" },
  { word: "salty", hint: "Taste of the sea" },
  { word: "spicy", hint: "Can feel hot in mouth" },
  { word: "sugar", hint: "Makes things sweet" },
  { word: "honey", hint: "Made by bees" },
  { word: "butter", hint: "Spread on bread" },
  { word: "cheese", hint: "Made from milk" },
  { word: "fruit", hint: "Sweet plant food" },
  { word: "grape", hint: "Small juicy fruit" },
  { word: "mango", hint: "Sweet tropical fruit" },
  { word: "lemon", hint: "Sour yellow fruit" },
  { word: "orange", hint: "Fruit and a color" },
  { word: "banana", hint: "Long yellow fruit" },
  { word: "tomato", hint: "Red cooking fruit" },
  { word: "carrot", hint: "Orange vegetable" },
  { word: "onion", hint: "Can make you cry" },
  { word: "pepper", hint: "Adds spice to food" },
  { word: "coffee", hint: "Keeps you awake" },
  { word: "bottle", hint: "Holds liquid" },
  { word: "basket", hint: "Carries items" },
  { word: "window", hint: "See outside through it" },
  { word: "door", hint: "Entry to a room" },
  { word: "floor", hint: "You walk on it" },
  { word: "ceiling", hint: "Above your head" },
  { word: "garden", hint: "Where plants grow" },
  { word: "street", hint: "Cars move on it" },
  { word: "market", hint: "Place to buy things" },
  { word: "store", hint: "Shop for items" },
  { word: "money", hint: "Used to buy things" },
  { word: "price", hint: "Cost of something" },
  { word: "value", hint: "Worth of something" },
  { word: "gift", hint: "Given freely" },
  { word: "party", hint: "Celebration event" },
  { word: "game", hint: "Played for fun" },
  { word: "sport", hint: "Physical activity" },
  { word: "team", hint: "Group working together" },
  { word: "score", hint: "Points in a game" },
  { word: "travel", hint: "Move between places" },
  { word: "journey", hint: "Trip from start to end" },
  { word: "ticket", hint: "Needed for entry" },
  { word: "train", hint: "Runs on tracks" },
  { word: "plane", hint: "Flies in the sky" },
  { word: "beach", hint: "Sandy sea area" },
  { word: "ocean", hint: "Huge salt water" },
  { word: "island", hint: "Land in water" },
  { word: "forest", hint: "Many trees together" },
  { word: "desert", hint: "Very dry land" },
  { word: "mountain", hint: "Very tall landform" },
  { word: "valley", hint: "Low land between hills" },
  { word: "sunset", hint: "Sun going down" },
  { word: "sunrise", hint: "Sun coming up" },
  { word: "shadow", hint: "Follows you but disappears in darkness" },
  { word: "mirror", hint: "Shows truth but never speaks" },
  { word: "whisper", hint: "A voice that hides itself" },
  { word: "puzzle", hint: "Complete it to understand it" },
  { word: "secret", hint: "Exists best when shared least" },
  { word: "memory", hint: "Lives in the past but shapes the present" },
  { word: "future", hint: "Always coming, never arriving" },
  { word: "danger", hint: "You don’t see it until it’s close" },
  { word: "escape", hint: "Leaving without being caught" },
  { word: "search", hint: "Looking without knowing where" },
  { word: "signal", hint: "A message without words" },
  { word: "vision", hint: "Seeing beyond just sight" },
  { word: "reason", hint: "The 'why' behind actions" },
  { word: "choice", hint: "Two paths, one decision" },
  { word: "effort", hint: "The price of achievement" },
  { word: "reward", hint: "What comes after effort" },
  { word: "chance", hint: "Luck disguised as randomness" },
  { word: "impact", hint: "A force that leaves a mark" },
  { word: "result", hint: "The end of a process" },
  { word: "method", hint: "A way to get things done" },
  { word: "random", hint: "Without pattern or plan" },
  { word: "hidden", hint: "There, but not seen" },
  { word: "silent", hint: "No sound, but presence" },
  { word: "broken", hint: "No longer whole" },
  { word: "stable", hint: "Does not easily change" },
  { word: "fragile", hint: "Easily damaged, handle with care" },
  { word: "strong", hint: "Hard to break or defeat" },
  { word: "simple", hint: "Easy to understand" },
  { word: "complex", hint: "Many parts, hard to grasp" },
  { word: "direct", hint: "Straight to the point" },
  { word: "twisted", hint: "Not straight in form or meaning" },
  { word: "pushed", hint: "Forced forward" },
  { word: "pulled", hint: "Drawn closer" },
  { word: "driven", hint: "Moved by force or desire" },
  { word: "guided", hint: "Shown the way" },
  { word: "fallen", hint: "Dropped from a higher place" },
  { word: "rising", hint: "Moving upward" },
  { word: "ending", hint: "Where everything stops" },
  { word: "begin", hint: "The very first step" },
  { word: "repeat", hint: "Do it again" },
  { word: "create", hint: "Bring something new into existence" },
  { word: "destroy", hint: "End something completely" },
  { word: "change", hint: "Become different" },
  { word: "remain", hint: "Stay the same" },
  { word: "follow", hint: "Go after something" },
  { word: "leader", hint: "Others move because of them" },
  { word: "player", hint: "Takes part in a game" },
  { word: "winner", hint: "Comes out on top" },
  { word: "losing", hint: "Not achieving victory" },
  { word: "battle", hint: "A fight between sides" },
  { word: "danger", hint: "Risk hiding in plain sight" },
  { word: "escape", hint: "Freedom through exit" },
  { word: "prison", hint: "Freedom is taken away here" },
  { word: "border", hint: "A line that separates" },
  { word: "nation", hint: "A group under one rule" },
  { word: "people", hint: "More than one person together" },
  { word: "family", hint: "Connected by blood or bond" },
  { word: "friend", hint: "Chosen, not assigned" },
  { word: "enemy", hint: "Stands against you" },
  { word: "trust", hint: "Belief without proof" },
  { word: "doubt", hint: "The enemy of certainty" },
  { word: "truth", hint: "What remains when lies fall" },
  { word: "false", hint: "Not real or true" },
  { word: "proof", hint: "Evidence that convinces" },
  { word: "logic", hint: "Thinking without emotion" },
  { word: "dream", hint: "Feels real until you wake" },
  { word: "night", hint: "When light disappears" },
  { word: "light", hint: "Removes the darkness" },
  { word: "sound", hint: "Heard but not seen" },
  { word: "voice", hint: "Carries words through air" },
  { word: "image", hint: "A picture without motion" },
  { word: "color", hint: "Gives life to visuals" },
  { word: "shape", hint: "Defines form and outline" },
  { word: "space", hint: "The area something occupies" },
  { word: "point", hint: "Has position but no size" },
  { word: "line", hint: "Connects two points" },
  { word: "angle", hint: "Formed by two lines meeting" },
  { word: "curve", hint: "A line that bends" },
  { word: "solid", hint: "Not liquid or gas" },
  { word: "fluid", hint: "Flows easily" },
];
